language: node_js
node_js:
  - stable
  - 7
before_script:
  - 'createdb -O postgres shelfgauge'
script: 'yarn lint && yarn test'
env:
  - 'DATABASE_URL=postgresql://postgres@localhost:5432/shelfgauge'
addons:
  postgresql: '9.4'
